
refLookup: references.yaml
pod5dir: /data1/ccmb/reuben/benchmarking/bacterial/datasets/pod5
filterChromosomes: true
tooling_dir: tooling

runControls: 
    experiments: [ HPJ99_WT ]
    runs: []
    accuracy: [ hac ]
    black_list_models : [5kHz_hac_v4r1_4mC]
    dorado_mod_models: 
      5mC:  []
      5mCG: []
      6mA:  []
      4mC:  []
    other_tools: 
      rockfish: []
      deepmod2_transformer: []
      deepmod2_bilstm: []
      f5c: []
      f5c_stranded: []
      deepbam:   []
      deepplant: []
    qc: 
      default_model   : v5r3
      tools: 
        nanostat: false
        nanoplot: false
        mosdepth: false
        nanoq: true

# TOOL RUN/SETUP CONFIGURATION
toolConfig: 
  dorado: 
    install_dir: dorado
    run_flags: --min-qscore 10
    dorado_version_map: 
      4kHz_v4: dorado-0.5.3
      5kHz_v4: dorado-0.9.1
      5kHz_v5: dorado-0.9.1
      5kHz_v5.2: dorado-1.1.1
    dorado_version_aliases: 
      dorado-0.5.3: dorado053
      dorado-0.9.1: dorado091
      dorado-1.1.1: dorado111
    model_dir: dorado_models
  rockfish: 
    install_dir: rockfish
    executable: rockfish
    conda: rockfish_test_nf
    model_dir: rockfishmodels
    model: rf_5kHz.ckpt
    call_flags: -b 8192 -d 0
  deepmod2: 
    install_dir: DeepMod2
    executable: deepmod2
    conda: deepmod2
    call_flags: --device=cuda --batch_size 2048
  f5c: 
    install_dir: f5c
    executable: f5c_x86_64_linux_cuda
    version: v1.5
    call_flags: --cuda-dev-id 0 -x hpc-high -K 2048 -B 40.0M --pore r10
  deepplant: 
    install_dir: /data1/tools/DeepPlant
    executable: build/DeepPlant
    conda: DeepPlant 
    model: /data1/tools/DeepPlant/model/bilstm/
    call_flags: 51 51 13 8 4 2048
    aggregation_flags: --threshold 0.5
  deepbam: 
    install_dir: /data1/tools/DeepBAM
    executable: cpp/build/DeepBAM
    conda: DeepBAM
    model: /data1/tools/DeepBAM/traced_script_module/LSTM_20240524_newfeature_script_b9_s15_epoch25_accuracy0.9742.pt
    call_flags: 51 8 4 2048 CG 0
    aggregation_flags: --threshold 0.5
  samtools: 
    cleanse_flags: -F 2304 --min-qlen 500
  modkit: 
    executable: modkit
    version: 0.5.1-rc1

timit: true
logit: true
